action: Add commitlint action for checking commits
red-hat-data-services/odf-operator pull request #20
Opened 2021-06-30 13:02 UTC by iamniting

Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

2021-06-30 13:13 UTC, iamniting commented
@jarrpa Let's merge this first so we can run this action on other PR's as well

2021-07-01 03:14 UTC, jarrpa requested changes
I thiiiink it looks fine? Unfortunately I don't any information to what commitlint is, where it's from, how it's configured, or what the parameters we're configuring specify. Also this seems like it's going to create a `conf` directory when we already have a `config` directory? That doesn't make much sense. Can the JSON config not live with the workflow YAML?

2021-07-01 07:46 UTC, iamniting commented
> I thiiiink it looks fine? Unfortunately I don't any information to what commitlint is, where it's from, how it's configured, or what the parameters we're configuring specify. Also this seems like it's going to create a `conf` directory when we already have a `config` directory? That doesn't make much sense. Can the JSON config not live with the workflow YAML?

commitlint makes sure that the commit message is as per our guidelines, here is the reference https://commitlint.js.org/#/reference-rules.

I have created a conf directory inside the `.github/workflows/` to place all action related conf files

2021-07-02 08:57 UTC, iamniting commented
Here are some examples
![Screenshot from 2021-07-02 14-23-14](https://user-images.githubusercontent.com/22993933/124249375-70fe4000-db41-11eb-9b8b-a57ca3321c0f.png)
![Screenshot from 2021-07-02 14-20-39](https://user-images.githubusercontent.com/22993933/124249365-6f347c80-db41-11eb-8023-b8a5645c0a38.png)
![Screenshot from 2021-07-02 14-25-33](https://user-images.githubusercontent.com/22993933/124249379-722f6d00-db41-11eb-8abd-3dfa83e186f0.png)

2021-07-06 05:37 UTC, iamniting commented
@jarrpa I am merging this one myself. We can change this later if required.

2021-07-06 05:37 UTC, merged